---
on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages
        
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: ruby/setup-ruby@77fe3b48b7ef9e181c0ecc9f05478ba7818b1b5c
        with:
          bundler-cache: true

      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-build-${{ env.cache-name }}-
            npm-${{ runner.os }}-build-
            npm-

      - name: Install NPM dependencies
        run: npm install

      - name: Test
        run: bundle exec rspec

      - name: Lint
        run: bundle exec rubocop --parallel

      - name: Validate schema
        run: bundle exec rake schema

      - name: Build
        run: bundle exec rake build

      - name: Upload built site
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: site
          path: build
          retention-days: 1

  htmlproofer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: ruby/setup-ruby@77fe3b48b7ef9e181c0ecc9f05478ba7818b1b5c
        with:
          bundler-cache: true

      - name: Download built site
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: site
          path: build

      - name: Test built site
        run: bundle exec rake htmlproofer

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: ruby/setup-ruby@77fe3b48b7ef9e181c0ecc9f05478ba7818b1b5c
        with:
          bundler-cache: true

      - name: Download built site
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: site
          path: build

      # Checkout stripped-down gh-pages branch to a subdirectory, for publishing
      - name: Checkout gh-pages branch
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: gh-pages
          path: tmp/publish

      - name: Publish
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          bundle exec rake publish CLONED_GH_PAGES_DIR="tmp/publish"
